Repository sullog-official/sullog-client, pull requests merged in 2023-04, with the labels that each got.

#56 refactor: TopNavigator 리팩토링
  src/pages/list/index.tsx
  src/pages/my-search/index.tsx
  src/shared/components/TopNavigator/TopNavigator.module.scss
  src/shared/components/TopNavigator/TopNavigator.stories.tsx
  src/shared/components/TopNavigator/TopNavigator.tsx
Labels: refactor

#57 feat: react-query 초기 세팅
  .pnp.cjs
  .storybook/preview.js
  .yarn/cache/@tanstack-match-sorter-utils-npm-8.8.4-488b98c113-d005f50075.zip
  .yarn/cache/@tanstack-query-core-npm-4.29.1-38b960e4c7-e7a5a73e5e.zip
  .yarn/cache/@tanstack-react-query-devtools-npm-4.29.3-a08e29cd32-fd52531b4e.zip
  .yarn/cache/@tanstack-react-query-npm-4.29.3-ace03b857b-7d33fe001b.zip
  .yarn/cache/copy-anything-npm-3.0.3-a24d77ec4d-d456dc5ec9.zip
  .yarn/cache/is-what-npm-4.1.8-57bef8cfbc-b9bec3acff.zip
  .yarn/cache/react-query-kit-npm-1.4.1-b7a1e62642-8054919042.zip
  .yarn/cache/remove-accents-npm-0.4.2-7cb341092a-84a6988555.zip
  .yarn/cache/superjson-npm-1.12.2-e37d205ed2-cf7735e172.zip
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  package.json
  src/pages/_app.tsx
  src/shared/apis/.gitkeep
  src/shared/configs/reactQuery.ts
  yarn.lock
Labels: feature, dev

#63 [REFACTOR] SearchBar 리팩토링
  src/assets/icons/filter.svg
  src/assets/icons/index.ts
  src/features/search/components/SearchBar/ChipContainer.tsx
  src/features/search/components/SearchBar/SearchBar.module.scss
  src/features/search/components/SearchBar/SearchBar.stories.tsx
  src/features/search/components/SearchBar/SearchBar.tsx
  src/pages/index.tsx
  src/shared/components/Button/Button.module.scss
Labels: enhancement

#68 feat: 경험 상세 페이지 api 연동
  src/features/record/components/AlcoholPercentFeelingInput/AlcoholPercentFeelingInput.tsx
  src/features/record/components/DetailFlavorInput/DetailFlavorInput.tsx
  src/features/record/components/DetailFlavorInput/flavorTagOptions.ts
  src/features/record/components/DetailFlavorInput/flavorTags.ts
  src/features/record/components/ImageSwiper/ImageSwiper.tsx
  src/features/record/utils/getAlcoholPercentFeelingLabel.ts
  src/features/record/utils/getFlavorTagLabel.ts
  src/pages/records/[id]/index.tsx
  src/shared/constants/flavorTags.ts
  src/shared/types/record/flavorTag.ts
Labels: feature

#67 [FEATURE] 둘러보기 페이지 개발
  src/assets/styles/global.scss
  src/features/feed/components/Card/Card.module.scss
  src/features/feed/components/Card/Card.stories.tsx
  src/features/feed/components/Card/Card.tsx
  src/features/feed/components/Card/index.ts
  src/pages/feed/index.module.scss
  src/pages/feed/index.tsx
  src/shared/components/BottomNavigator/BottomNavigator.tsx
Labels: feature
