Repository sullog-official/sullog-client, pull requests merged in 2023-05, with the labels that each got.

#84 [FEATURE] useIntersect 훅 작성 및 피드 페이지에 무한 스크롤 적용
  next.config.js
  src/pages/feed/index.tsx
  src/shared/apis/feed/getFeed.ts
  src/shared/hooks/.gitkeep
  src/shared/hooks/useIntersect.ts
Labels: feature

#86 feat: Skeleton 컴포넌트 추가
  src/shared/components/Skeleton/Skeleton.module.scss
  src/shared/components/Skeleton/Skeleton.stories.tsx
  src/shared/components/Skeleton/Skeleton.tsx
  src/shared/components/Skeleton/index.ts
Labels: feature

#88 feat: PageLayout 추가 및 전체 페이지 레이아웃 리팩터링
  src/assets/styles/global.scss
  src/assets/styles/themes/_index.scss
  src/assets/styles/themes/_layout.module.scss
  src/features/search/components/AlcoholCategoryTab/AlcoholCategoryTab.module.scss
  src/features/search/components/RecentSearches/RecentSearches.module.scss
  src/pages/alcohols/search/index.module.scss
  src/pages/alcohols/search/index.tsx
  src/pages/feed/index.module.scss
  src/pages/feed/index.tsx
  src/pages/index.module.scss
  src/pages/index.tsx
  src/pages/login/index.module.scss
  src/pages/login/index.tsx
  src/pages/my/records/index.module.scss
  src/pages/my/records/index.tsx
  src/pages/my/records/search/index.module.scss
  src/pages/my/records/search/index.tsx
  src/pages/records/[id]/index.tsx
  src/pages/records/create/index.tsx
  src/shared/components/BottomNavigator/BottomNavigator.module.scss
  src/shared/components/PageLayout/PageLayout.module.scss
  src/shared/components/PageLayout/PageLayout.tsx
  src/shared/components/PageLayout/index.ts
  src/shared/components/TopNavigator/TopNavigator.module.scss
  src/shared/components/TopNavigator/TopNavigator.tsx
Labels: refactor

#100 [FIX] 로컬 폰트가 로드되지 않는 이슈
  src/assets/styles/fonts/index.ts
Labels: bug

#101 [FEATURE] Skeleton 추가
  src/pages/feed/index.tsx
Labels: feature

#102 [FEATURE] 로그인 시 토큰 세팅하는 UI
  src/pages/login/index.module.scss
  src/pages/login/index.tsx
Labels: feature
